- name: conditions demo
  hosts: local
  connection: local
  vars:
    number: 70
  tasks:
    - name: print number is less than or equal to 100
      ansible.builtin.debug:
        msg: "Given number {{ number }} is less than 100"
      when: number < 100

    - name: Print number is greater than or equal to 100
      ansible.builtin.debug
        msg: "Given number {{ number }} is greater than 100"
      when: number > 100

