- name: Playbook for os family
  hosts: frontend
  become: yes
  connection: ssh
  tasks:
  - name: Install nginx in redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install nginx in redhat
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
